SorteoApp/Models/Base.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace SorteoApp.Models
{
    public class Base
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }
}

SorteoApp/Models/ErrorViewModel.cs
namespace SorteoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SorteoApp/Models/Participante.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using SorteoApp.Validaciones;

namespace SorteoApp.Models
{
    public class Participante : Base
    {
        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [StringLength(maximumLength: 20, MinimumLength = 2, ErrorMessage = "La longitud del campo debe estar entre {2} y {1}")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [StringLength(15)]
        [Display(Name = "Apellido")]
        public string Apellido { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [EmailAddress]
        [Display(Name = "e-mail")]
        public string Email { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [Display(Name = "DNI")]       
        public string Dni { get; set; }  //<--- Esto o lo cambio a string o busco de hacer una validacion personalizada o buscar una validacion par ael error que sale



        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [Display(Name = "Dirección")]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [Display(Name = "Codigo Postal")]
        public int CodigoPostal { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [Display(Name = "Localidad")]
        public string Localidad { get; set; }

        
        [Display(Name = "Provincia")]
        [Provincia]
        public string Provincia { get; set; }


        
        [Required(ErrorMessage = "El campo {0} es requerido..")]
        [Display(Name = "Acepto")]
        [Terminos]
        public bool Legal { get; set; }
    }
}

SorteoApp/Controllers/HomeController.cs
using System;
using System.Linq;
using SorteoApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SorteoApp.Data;
using System.Diagnostics;

namespace SorteoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

SorteoApp/Controllers/ParticipantesController.cs
using Microsoft.AspNetCore.Http;
using SorteoApp.Models;
using SorteoApp.Data;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System;
using static SorteoApp.Models.Participante;
using System.Configuration;



namespace SorteoApp.Controllers
{
    public class ParticipantesController : Controller
    {
        private ApplicationDbContext _context;
        public ParticipantesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Formulario()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registro(Participante participante, string nombre, 
                                      string apellido, string dni, string direccion, 
                                      string email, int codigopostal, string localidad, 
                                      string provincia, bool legal) //Participante participante, string nombre, string apellido, string dni, string direccion, string email, int codigopostal, string localidad, string provincia, bool confirmar
        {

            Participante oParticipante = new Participante()
            {

                Nombre = nombre,
                Apellido = apellido,
                Dni = dni,
                Email = email,
                Direccion = direccion,
                CodigoPostal = codigopostal,
                Localidad = localidad,
                Provincia = provincia,
                Legal = legal
            };
            
            if (!ModelState.IsValid)
            {
                return View("Formulario", participante);
            };
            
            _context.Participantes.Add(oParticipante);        
            _context.SaveChanges();


            return View("Registro");  

        }


        public IActionResult Inscriptos()
        {
            ViewBag.Cantidad = _context.Participantes.Count();

            return View();
        }
    
        public IActionResult Selector()
        {
            return View();
        }

        public IActionResult Resultado()
        {
            //lista DNI en pantalla
            //ViewBag.SelectorGanador = _context.Participantes.OrderByDescending(x => x.Dni).ToList();

            //selecciona nombre y apellido y lo muestra en pantalla
            //Creo variable random
            Random rand = new Random();
            //selecciono un numero random desde el 0 hasta el numero maximo de inscriptos en la bdd
            var randoms = rand.Next(0, _context.Participantes.Count());
            //skip(saltea random) - Take(toma 1) - Select(selecciona x de x.nombre - FirstOrderDefault(devuelve la primera de una lista o null si no encuentra coincidencia)
            var nombre = _context.Participantes.Skip(randoms).Take(1).Select(p => p.Nombre).FirstOrDefault();
            var apellido = _context.Participantes.Skip(randoms).Take(1).Select(p => p.Apellido).FirstOrDefault();
            var dni = _context.Participantes.Skip(randoms).Take(1).Select(p => p.Dni).FirstOrDefault();
            var provincia = _context.Participantes.Skip(randoms).Take(1).Select(p => p.Provincia).FirstOrDefault();
            var localidad = _context.Participantes.Skip(randoms).Take(1).Select(p => p.Localidad).FirstOrDefault();
            ViewBag.RandomNombre = nombre;
            ViewBag.RandomApellido = apellido;
            ViewBag.RandomDni = dni;
            ViewBag.RandomProvincia = provincia;
            ViewBag.RandomLocalidad = localidad;
            return View();
        }

    }
}

SorteoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="container-fluid">
    <div class="row">
        <div class="colum-1 col-ms-1 col-md-8 text-center d-flex flex-column justify-content-center align-content-center">
            <h1 class="display-4 py-3">BIENVENIDOS AL SORTEO</h1>
           <a asp-action="Formulario" asp-controller="Participantes" type="button" class="btn btn-outline-info mb-5">PARTICIPAR</a>
           
        </div>

        <div class="colum-2 col-ms-1 col-md-4 text-center text-sm-start p-3">  
            <h6>BASES Y CONDICIONES DEL SORTEO</h6><br />
            <P>Para participar del sorteo, el interesado deberá completar el 
                <a href="#">FORMULARIO</a>
            </P>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>Cada participante deberá completar el mismo con sus datos personales, nombre completo, fecha de nacimiento, DNI, correo electrónico, un número de celular y un mail de contacto.</p>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>olo podrán participar personas físicas MAYORES DE 18 AÑOS.</p>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>El sistema le otorgará a cada participante un número único e irrepetible, por persona.<br /></p>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>A cada uno de los concursantes se les enviará un correo electrónico a modo de confirmación, entre los datos que aparecerán en el correo estará el número que el sistema le ha otorgado como así también los datos pertinentes del sorteo al cual se inscribió.</p>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>En el sitio www.javiermilei.com, además de inscribirse también se podrá visualizar un listado de personas ya inscriptas. Los datos de los participantes no serán visibles en su totalidad para preservar la identidad de los mismos.</p>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>El propio programa elegirá de forma aleatoria entre todos los concursantes un ganador.</p>
                <p><img class="icon-confirm" src="~/assets/check.svg"/>Los datos correspondientes al ganador serán verificados por ESCRIBANO PÚBLICO dando veracidad a los mismos.</p>
        </div>
        <div class="colum-3 col-12">    
            <h1> PREMIO USD$100.0000</h1>
        </div>
    </div>
</div>

SorteoApp/Views/Participantes/Formulario.cshtml
@model Participante
@{
    ViewData["Title"] = "Formulario";
}
<section class="form-container">

    <h1>@ViewData["Title"]</h1>

    <a asp-action="Index" asp-controller="Home" class="btn btn-primary">Volver</a>

    <p> Los datos ingresados serán tomados en cuenta para que usted pueda acceder a su premio.<br />
    y no serán expuestos al público para su seguridad.
    </p>


    <form class="row g-3" method="post" asp-controller="Participantes" asp-action="Registro">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="col-md-6">
        <label asp-for="Nombre" class="form-label"></label>
        <input asp-for="Nombre" type="text" class="form-control" id="inputEmail4" placeholder="Ingrese su nombre...">
        <span asp-validation-for="Nombre" class="text-danger"></span>
      </div>
      <div class="col-md-6">
        <label asp-for="Apellido" class="form-label"></label>
        <input asp-for="Apellido" type="text"  class="form-control" id="inputPassword4" placeholder="Ingrese su apellido...">
        <span asp-validation-for="Apellido" class="text-danger"></span>
      </div>
      <div class="col-md-6">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" type="email" class="form-control" id="inputEmail4" placeholder="ejemplo@gmail.com">
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      <div class="col-md-6">
        <label asp-for="Dni" class="form-label"></label>
        <input asp-for="Dni" type="number" class="form-control" id="inputPassword4" placeholder="Numero de documento...">
        <span asp-validation-for="Dni" class="text-danger"></span>
      </div>
      <div class="col-12">
        <label asp-for="Direccion" class="form-label"></label>
        <input asp-for="Direccion" type="text" class="form-control" id="inputAddress" placeholder='Ejemplo: "Av. Rivadavia 123" '>
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>
      <div class="col-12">
        <label asp-for="CodigoPostal" class="form-label"></label>
        <input asp-for="CodigoPostal" type="number" class="form-control" id="inputAddress2" placeholder="Ingrese su codigo postal...">
        <span asp-validation-for="CodigoPostal" class="text-danger"></span>
      </div>
      <div class="col-md-6">
        <label asp-for="Localidad" class="form-label"></label>
        <input asp-for="Localidad" type="text" class="form-control" id="inputCity" placeholder="Localidad de residencia..">
        <span asp-validation-for="Localidad" class="text-danger"></span>
      </div>
      <div class="col-md-4">
        <label asp-for="Provincia" class="form-label"></label>
        <select asp-for="Provincia" class="form-control">
            <option selected>...</option>
            <option >Buenos Aires</option>
            <option >CABA</option>
            <option >Misiones</option>
            <option >Corrientes</option>
            <option >Entre Rios</option>
            <option >Chaco</option>
            <option >Córdoba</option>
            <option >Tierra del Fuego</option>
            <option >Santa Fe</option>
            <option >Rio Negro</option>
            <option >La Pampa</option>
            <option >Chubut</option>
            <option >Mendoza</option>
            <option >Salta</option>
            <option >Tucumán</option>
            <option >Jujuy</option>
            <option >San Luis</option>
            <option >San Juan</option>
            <option >Neuquén</option>
            <option >Santa Cruz</option>
            <option >Catamarca</option>
            <option >La Rioja</option>
            <option >Santiago del Estero</option>
            <option >Formosa</option>  
        </select>
        <span asp-validation-for="Provincia" class="text-danger"></span>
      </div>

      <div class="col-12">
        <div class="form-check">
          <p>Estoy de acuerdo en compartir mi información con el uso exclusivo del sorteo.</p>
          <input asp-for="Legal" class="form-check-input" type="checkbox" id="gridCheck">
          <label asp-for="Legal" class="form-check-label" for="gridCheck"></label>
          <span asp-validation-for="Legal" class="text-danger"></span>
        </div>
      </div>

      <div class="col-12">
        <button type="submit" class="btn btn-primary">Enviar</button>
      </div>
    </form>

</section>

SorteoApp/Views/Participantes/Inscriptos.cshtml
<h1> Inscriptos a la fecha</h1>
<h1>@ViewBag.Cantidad</h1>

<h1> El sorteo finaliza el 10/10/2010</h1>

SorteoApp/Views/Participantes/Registro.cshtml
@model Participante

<h1> REGISTRO EXITOSO </h1>
<h6>El usuario fué registrado con exito.</h6>

SorteoApp/Views/Participantes/Resultado.cshtml
<div class="contador-fade"></div>

<div class="cont">   
    <h1 class="ganador">El ganador es...</h1>          
    <h1 class="uno conteo">1</h1>
    <h1 class="dos conteo">2</h1>
    <h1 class="tres conteo">3</h1>     
</div>

<div class="box-selector col-ms-1">
    <h3>FELICITACIONES </h3>
    <h1>@ViewBag.RandomNombre @ViewBag.RandomApellido </h1>
    <h3>GANASTE!</h3>
    <table>
        <thead>
            <tr class="list-selector">
                <th>DNI: @ViewBag.RandomDni</th>
                <th>Provincia: @ViewBag.RandomProvincia </th>
                <th>Localidad: @ViewBag.RandomLocalidad </th>
            </tr>
        </thead>
    </table>
    <div class="colum-1 col-ms-1 col-md-8 text-center d-flex flex-column justify-content-center align-content-center">
        <a asp-action="Resultado" asp-controller="Participantes" type="button" class="btn btn-outline-info mb-5">OTRO GANADOR</a>           
    </div>  
</div>

SorteoApp/Views/Participantes/Selector.cshtml
@model Participante
<p> En esta vista se verá una aplicación
    que seleccionará aleatoriamente un numero
    
    
    dentro de todos los usuarios registrados
    al sorteo.
    (Se considera la posibilidad de compartir el codigo
    encargado de seleccionar el numero aleatorio para
    que los usuarios puedan ver que efectivamente
    funciona sin intencionalidad de trasforndo.)
</p>

<!--
foreach(var item in ViewBag.SelectorGanador)
{
    <h1>item.Dni </h1>
} TENGO QUE PONER LAS ARROBAS EN FOREACH ITEM Y VIEWBAG PARA USAR
-->

<div class="col-ms-1 col-md-8 text-center d-flex flex-column justify-content-center align-content-center">
    <a asp-action="Resultado" asp-controller="Participantes" type="button" class="btn btn-outline-info mb-5">BOTON</a>           
</div>

SorteoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SorteoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SorteoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-0 bg-navcolor">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">AppSorteo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Participantes" asp-action="Formulario">Formulario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Participantes" asp-action="Inscriptos">Inscriptos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Participantes" asp-action="Selector">Selector</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid m-0 p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center bg-navcolor">
        <div class="container-fluid">
            &copy; 2022 - SorteoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>